### ISSUE TITLE
Shape changes after multiple steps

### ISSUE THREAD

**Issue by sherlongqu** [Xiaokang2022/Intelligent-Magic-Cube#1]
![image](https://github.com/Xiaokang2022/Intelligent-Magic-Cube/assets/96058209/660ef55e-1ecd-4ab0-abca-7255ab99ffa0)

**Comment by Xiaokang2022** [comment]
In general, this does not happen. This is only possible if your computer is running slowly and the program is spinning the Rubik's Cube. The specific explanation is that the next rotation operation has already started before the Rubik's Cube has completed the previous rotation operation (due to the slow running of the program).

However, there should be a solution for this, and I'll take the time to look into it.

**Comment by Xiaokang2022** [comment]
Reducing the frame rate of the animation may help your problem, but to solve the problem fundamentally, you need to modify the `Animation` class of `tkintertools`.

I'm no longer updating and maintaining `tkintertools` 2, so this issue won't be resolved. But I'll document this issue and avoid it in `tkintertools` 3.

By the way, you can modify the size of the default frame rate by modifying the value of `tkintertools.constant.FPS`.

**Comment by sherlongqu** [comment]
ok Thank You
